### PR TITLE
Update dependencies (including `bson`) and have Travis use latest releases

### PR DESCRIPTION
**Pull request by saghm**
This contains the long-awaited changes in #140, as well as a few other updates

### CODE REVIEW

**Comment by kyeah** [comment]
LGTM -- pinging @vkarpov15.

**Comment by vkarpov15** [comment]
LGTM :beers:

**Comment by vkarpov15** [comment]
@saghm is this ready to push up to crates.io?

**Comment by saghm** [comment]
Yep, I think so!

**Pull request merged**
