### PR TITLE
WIP: Change streams.

### LINKED ISSUE #246: 3.6 Change Streams
Any rough sense of when these might be supported?  thank you!

https://docs.mongodb.com/manual/tutorial/change-streams-example/

### PR DESCRIPTION
**Pull request by thedodd**
Initial implementation is done. There is only one caveat to the implementation: it does not take into account the `max wire version`. I've requested feedback on how to move forward with this. Otherwise, this PR is open for feedback/review. 

### todo
- [ ] need to track down how to get `max wire version`. There are a few TODOs in the code where this is required.
- [ ] tests. Basic unit tests for various functions in the code & implement the testing strategy in the spec.
- [ ] have @saghm &| @kyeah review the `is_error_recoverable` routine to ensure it is spec compliant.

Closes #246 

----

The [change streams spec is here](https://github.com/mongodb/specifications/blob/master/source/change-streams/change-streams.rst).

### CODE REVIEW

**Comment by thedodd** [comment]
@saghm && @kyeah the initial implementation of change streams is done. If you guys don't mind taking a look that would be super awesome. 

A few things I could use some help with, as described in the `TODO`s above:
- what do you think would be the best way to track down and use the `max wire version`. The spec requires that it is taken into account under a few conditions, which are accounted for in the code right now, but only as placeholders. We need to find the best way to track this down.
- I wasn't able to find an existing pattern for killing a cursor, and I didn't see anything related to such cleanup happening on `drop`. I'm happy to implement a pattern, but I just wanted to get feedback from you guys first. This is required according to the spec when a recoverable error was encountered and we need to build a new cursor. Spec requires that we issue a kill command on the old cursor & ignore the result thereof.
- lastly, the `is_error_recoverable` routine is a little brute ... perhaps it is spot on, but the way the errors are organized in this crate right now have lead me to just implement it as is for now. I'm happy to take it to the next level, I just didn't want a massive sprawling `match` block `:)`, but I'll do whatever is needed.

**Comment by cherryland** [comment]
Bump

**Comment by cherryland** [comment]
bump

**Comment by thedodd** [comment]
@cherryland hey, sorry that this has taken so long to land. If you would like, I can rebase this branch so that you could check it out and start using it.

I tested it out on standalone and replica set deployments, works quite well.

**Comment by MartenCatcher** [comment]
@thedodd Hi! Thank you a lot for your work. I need this feature for my project. How can I support?

**Comment by thedodd** [comment]
@MartenCatcher well, the feature works quite well. So you could just pin to this branch in your Cargo.toml.

As far as getting this PR to land, I do believe that this project is EOL (a new driver is being developed). So the above option is probably best, short of forking the entire project and running with it.

**Comment by MartenCatcher** [comment]
@thedodd what the project are you talking about? Can you give me a link to a repo?

**Comment by saghm** [comment]
To clarify, myself and my team at MongoDB are working towards an alpha release of an officially supported Rust driver. We plan on open sourcing it once we release the alpha, so unfortunately there isn't a repo I can point you towards currently. Once it is released, it will live at github.com/mongodb/mongo-rust-driver.

**Comment by MartenCatcher** [comment]
@saghm thank you for the insight. Great news!

**Comment by saghm** [comment]
Hello everyone! We've just released an alpha of [an official MongoDB Rust driver](https://github.com/mongodb/mongo-rust-driver); you can read about it [here](https://www.mongodb.com/blog/post/announcing-the-official-mongodb-rust-driver)! Because of this, we won't be updating this driver anymore, and the repository will be made read-only as soon as I get finished posting these messages. Thanks for using this driver, and we hope you try out the new one!

**Pull request closed without merging**
